[workspace]
channels = ["conda-forge"]
name = "pixi"
platforms = [{ name = "linux-64-cuda", platform = "linux-64", cuda = "12" }]
requires-pixi = ">=0.71.0"
version = "0.1.0"

[tasks.train]
description = "Train a PyTorch CNN classifier on the MNIST dataset"
cmd = "python ./main.py --epochs 20 --save-model"

[dependencies]
pytorch-gpu = ">=2.12.1,<3"
torchvision = ">=0.27.1,<0.28"
cuda-version = "12.9.*"
