universe = vanilla

log = job_4.log
#
executable = run_parallel.sh

output = out_4.out
error = err_4.err
#
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = http://proxy.chtc.wisc.edu/SQUID/gpu-examples/Miniconda3-latest-Linux-x86_64.sh,../env.yml,model_parallel.py


require_gpus = (Capability == 7.5) && (11.1 <= DriverVersion)
request_cpus = 1
request_gpus = 4
request_memory = 16GB
request_disk = 40GB

+WantGPULab = true
+GPUJobLength = "short"

queue 1
