[workspace]
channels = ["conda-forge"]
name = "pixi"
platforms = ["linux-64"]
version = "0.1.0"

[tasks.train]
description = "Train a PyTorch CNN classifier on the MNIST dataset"
cmd = "python ./main.py --epochs 20 --save-model"

[dependencies]
pytorch-gpu = ">=2.7.1,<3"
torchvision = ">=0.24.0,<0.25"
cuda-version = "12.9.*"

[system-requirements]
cuda = "12.9"
